// 数据相关变量
export const dataFileList = // 数据列表
[
    {
        type: 'road',
        label: '路网数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'building',
        label: '建筑物数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'dem',
        label: '高程数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["tif", "ovr", "tfw", "xml"],
    },
    {
        type: 'precipitation',
        label: '年降水数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'water',
        label: '水文数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'od',
        label: '交通出行量数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["csv", "xlsx"],
    },
    {
        type: 'hospital',
        label: '医疗设施数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'community',
        label: '居民区数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'stationpoint',
        label: '通讯基站点数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'stationarea',
        label: '通讯基站面数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["shp", "cpg", "dbf", "prj", "qix", "sbn", "sbx", "shx", "xml"],
    },
    {
        type: 'validation',
        label: '实际涝点数据',
        files: [],
        filesInfo: [],
        status: false,
        extensions: ["xls", "xlsx", "csv"],
    }
];